### ISSUE TITLE
Handle the error to overcome github/dns fluctuations

### ISSUE THREAD

**Issue by sgriffith3** [alta3/ssh-githugger#1]
https://github.com/alta3/ssh-githugger/blob/a224c2cd8d08f360f4f800672b4e0ea042f8703a/lib/authorized_key.py#L38

The connection did not return the expected data and threw an error. Please handle this error more gracefully.

**Comment by sfeeser** [comment]
@sgriffith3, is this a duplicate of #1?
I have number 1 addressed and I can replicate this problem as the program now gracefully fails when given bad data.

**Comment by sfeeser** [comment]
Duplicate of  the rate limit issue #2
