### ISSUE TITLE
Create ENV_VARS for each cli argument flag

### ISSUE THREAD

**Issue by bryfry** [alta3/ssh-githugger#18]
Copied from [PR feedback](https://github.com/alta3/ssh-githugger/pull/17#pullrequestreview-622656192) - this issue is the env portion.
- As a user running this script from the cli I want to be able to provide parameters for any/all functionality without switching to env_vars
- Every cli argument should have a complementary env_var (documented in it's help line) 
- If both are provided (cli flag and ENV) the environment should win
- Our service based invocations should only use env vars, not flags

**Comment by sfeeser** [comment]
@bryfry , how do I pass the environment?  See the last commit. Line 64 ssh-githugger.py. The environment is expected in Andrew's code.

**Comment by bryfry** [comment]
Check andrews server.py, it grabs the whole environment and passes it into the class init
