### ISSUE TITLE
Overcome API Rate Limitations

### ISSUE THREAD

**Issue by sgriffith3** [alta3/ssh-githugger#2]
**After** adding a print function to the code, I was able to find that I was attempting to run this code too often for GitHub's liking. Instead of returning the expected values, GitHub was sending a message saying that the API rate limit has been exceeded.

```
 {'message': "API rate limit exceeded for <REDACTED-IP-ADDRESS> (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}
Traceback (most recent call last):
  File "ssh-copy-id-from-github.py", line 53, in <module>
    loop.run_until_complete(ak.collect_keys())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sam/ssh-githugger/lib/authorized_key.py", line 40, in collect_keys
    user_keys = [Key(**k, user=user) for k in data]
  File "/home/sam/ssh-githugger/lib/authorized_key.py", line 40, in <listcomp>
    user_keys = [Key(**k, user=user) for k in data]
TypeError: type object argument after ** must be a mapping, not str
```

To summarize what the rate limitations are:

|Authentication Level | Limit |
|---|---|
|Unauthenticated | 60 per hour |
|Authenticated | 5000 per hour |

By attempting to run this job on a cron job set to check every minute( * * * * *) on one machine, I am using up all 60 of my unauthenticated requests.

I see two viable solutions here:
1. Authenticate with GitHub prior to sending requests OR
2. Limit the cron job to occur on a much less regular schedule (such as every day at the hour and minute that it is when the job gets created)

@bryfry, I am not sure which path we want to take, so I am just assigning this to you for your consideration.

**Comment by bryfry** [comment]
Both things we should do:
- [ ] Create a mechanism for ssh-githugger to use an oauth token (zero scope is probably required)
- [ ] Create a new repo that mirror's public keys into a self hosted github api with only that key endpoint served

Other investigations:
- [ ] look into github events to webhook on key change events

**Comment by bryfry** [comment]
@sgriffith3 re-assigning this to you because I think you've done (completed?) the public key mirror.

**Comment by bryfry** [comment]
If we've got the 2nd option done, let's update this issue to be about documentation and add a section to the README which documents:
- If you're running this on N > X systems you will have this issue
- How we overcame the issue by using a mirror

**Comment by sfeeser** [comment]
The Problem
Read this first: https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting

The manual solution:
Then read this: https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#authentication

The automated solution
Then read this: https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#web-application-flow

What the above says is: 
 - You get 60 unauthenticated API calls per hour per IP address.
 - You get 5000 authorized APU calls per hour with authentication (login/password)
 - The only way to do this is to manually obtain a token, then apply that token on API calls to get 5000 per hour, no IP address checking.

None of these things sounds attractive.  I think a key management solution is required that works for us.

**Comment by bryfry** [comment]
This isn't the first API key that we need to deploy into our environments.
We have two that get deployed with live. I think we need to solve in a
standardize way this deployment problem that we keep avoiding solving.

Using a sid (bot) user to generate the API key with no access to anything
but the key api could be a good solution for us. Even if we use that user
to only update some other source of unauthenticated public key source
without rate limits (keys.alta3.com).

**Comment by sfeeser** [comment]
Please begin testing the undercloud_v1.1 version. It now addresses rate limits.
Test:
Install the undercloud_v1.1 version
Run the program until the rate limit is exceeded.
The system should time-out as follows:
First try will wait countdown time plus 60 seconds
Second try (back to back rate limit) countdown time plus 50 seconds
Third Try (back to back rate limit) countdown time plus 40 second
And so on until
Sixth try (5 back to back attempts that were all rate limited) countdown time.

If this works, we start with this as our base for new issues.
